### ISSUE TITLE
Object access

### ISSUE THREAD

**Issue by khc** [SE7ENSKY/jade2php#1]
There is a problem with compiling objects to PHP. The following Jade code:

```
- var a = array[0]
- var b = array['index']
- var c = object.property
- var d = object.method()
```

is compiled to:

```
<?php $a = $array[0] ?>
<?php $b = $array['index'] ?>
<?php $c = $object['property'] ?>
<?php $d = $object['method']() ?>
```

although I think the two last lines should look like:

```
<?php $c = $object->property ?>
<?php $d = $object->method() ?>
```

jade2php depends on your library js2php where the code is generated properly. I've checked using  the online demo.

**Comment by ivankravchenko** [comment]
This particular thing is hard-coded [here](https://github.com/SE7ENSKY/jade2php/blob/master/src/jsExpressionToPhp.coffee#L19) and preferred on my environment.
I think this should be an option, correct?

**Comment by khc** [comment]
Yes, an option would be great. I'm using jade2php with WordPress and casting every object to array is troublesome, but accessing methods is impossible.

**Comment by ivankravchenko** [comment]
I am using with WordPress too, but with arrays (and some custom data model code) :)

**Comment by ivankravchenko** [comment]
Bumped version to 1.1.4.
Added --no-arrays-only CLI option and arraysOnly: false option [here](https://github.com/SE7ENSKY/jade2php/commit/09c4ad03d4b83535c0e8a7b096d10db2ce01413b).
Please review and make me know it is what you requested :)

**Comment by khc** [comment]
Something not right (or I'm doing something wrong)

```
git clone https://github.com/SE7ENSKY/jade2php.git
cd jade2php
npm update
echo '- var a = object.property' | bin/jade2php --no-arrays-only --omit-php-runtime --omit-php-extractor
```

And the result is:

```
<?php $a = $object['property'] ?>
```

My environment: OSX 10.9.4, node 0.10.35 (installed with brew)

**Comment by endel** [comment]
Hey guys,

I've made some updates on js2php since the @ivankravchenko's fork. I suggest you to pull the changes if it doesn't break anything.

**Comment by ivankravchenko** [comment]
Thanks you, guys.
@khc , that was my stupid code typo, fixed in 1.1.5 (5b9aa8d).
@endel , switched to your original js2php implementation.

**Comment by ivankravchenko** [comment]
@endel , I suggest you check [jsExpressionToPhp.coffee](https://github.com/SE7ENSKY/jade2php/blob/master/src/jsExpressionToPhp.coffee)
I've written this mess to handle some quirks.
May be some of that work bring ideas on js2php improvements.

**Comment by ivankravchenko** [comment]
@khc , please let me know if current implementation is sufficient for you.

**Comment by janwirth** [comment]
i still get the object[key] notation in my rendered php files..

**Comment by khc** [comment]
Everything is working now:

```
echo '- var a = object.property' | jade2php --no-arrays-only --omit-php-runtime --omit-php-extractor
```

gives

```
<?php $a = $object->property ?>
```
